apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: gcr.io/v4all-estate/re-api:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          env:
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                key: ConnectionStrings__DefaultConnection
                name: mysql-api-database
          - name: Authorization__AuthorityUrl
            value: https://identity.estatetify.com
          - name: Authorization__Audience
            value: realestate-api
      # imagePullSecrets:
      #   - name: gcr-json-key
---

apiVersion: v1
kind: Service
metadata:
  name: api-service

spec:
  selector:
    app: api

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    # - name: https
    #   protocol: TCP
    #   port: 443
    #   targetPort: 443

  type: ClusterIP
