apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-deployment
spec:
  selector:
    matchLabels:
      app: public
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: public
    spec:
      containers:
        - name: public
          image: gcr.io/v4all-estate/re-public:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          env:
          - name: VUE_APP_IDENTITY_URL
            value: https://identity.estatetify.com
          - name: VUE_APP_API_URL
            value: https://api.estatetify.com
          - name: VUE_APP_CLIENT_URL
            value: https://estatetify.com
      # imagePullSecrets:
      #   - name: gcr-json-key
---

apiVersion: v1
kind: Service
metadata:
  name: public-service

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: public

  ports:
    - name: http
      port: 80
      targetPort: 80

  type: ClusterIP
