networks:
  dmz-net:
    external:
      name: shared-dmz-network
services:
  shared-proxy:
    deploy:
      placement:
        constraints:
        - node.platform.os == linux
      replicas: 12
    image: sixeyed/shared-proxy
    networks:
      dmz-net: null
    ports:
    - mode: ingress
      published: 80
      target: 80
version: '3.3'

