version: '3.3'

services:
      
  shared-proxy:
    ports:
      - mode: ingress
        published: 80
        target: 80
    deploy:
      replicas: 12
      placement:
        constraints:
        - node.platform.os == linux

networks:
  dmz-net:
    external:
      name: shared-dmz-network