apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: estatetify-tls
spec:
  secretName: estatetify-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: estatetify.com
  dnsNames:
    - estatetify.com
    - www.estatetify.com
    - manage.estatetify.com
    - identity.estatetify.com
    - api.estatetify.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - estatetify.com
          - www.estatetify.com
          - manage.estatetify.com
          - identity.estatetify.com
          - api.estatetify.com