version: '3.1'

services:

  # nginx:
  #   restart: always
  #   build: 
  #     dockerfile: Dockerfile
  #     context: ./nginx
  #   ports:
  #     - "7050:80"

  mgt:
    build:
      dockerfile: Dockerfile
      context: ./ui/management
      args:
        - VUE_APP_IDENTITY_URL=http://192.168.0.4:7000
        - VUE_APP_API_URL=http://192.168.0.4:7001
        - VUE_APP_CLIENT_URL=http://192.168.0.4:7080
    image: my-registry:55000/re-mgt:latest
    ports:
      - "7080:80"
    
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    image: my-registry:55000/re-api:latest
    ports:
      - "7001:80"

  ids:
    # build:
    #   dockerfile: Dockerfile
    #   context: ./identity
    #   args:
    #     - CONNECTION_STRING=Server=192.168.0.4;Database=RealEstate;User=sa;Password=Welcome1;
    #     - REDIRECT_URIS=http://192.168.0.4:7080/LoginRedirect,http://192.168.0.4:7080/silent-redirect.html,http://192.168.0.4:7001/swagger/oauth2-redirect.html
    #     - POST_LOGOUT_REDIRECT_URIS=http://192.168.0.4:7080
    #     - ALLOWED_CORS_ORIGINS=http://192.168.0.4:7080,http://192.168.0.4:7001,http://192.168.0.4:7000
    #     - ISSUER=http://192.168.0.4:7000
    image: my-registry:55000/re-ids:latest
    ports:
      - "7000:80"
    # environment: 
    #   - ConnectionStrings__DefaultConnection=Server=192.168.0.4;Database=RealEstate;User=sa;Password=Welcome1;
    #   - ManagementClientConfiguration__RedirectUris=http://192.168.0.4:7080/LoginRedirect,http://192.168.0.4:7080/silent-redirect.html,https://192.168.0.4:7001/swagger/oauth2-redirect.html
    #   - ManagementClientConfiguration__PostLogoutRedirectUris=http://192.168.0.4:7080
    #   - ManagementClientConfiguration__AllowedCorsOrigins=http://192.168.0.4:7080, https://192.168.0.4:7001 http://192.168.0.4:7000
    #   - Issuer=http://192.168.0.4:7000